Fix coloring in most places, add posting to slack on feature/hotfix/release finish, remove automatic versioning

diff --git a/post-flow-release-finish b/post-flow-release-finish
--- a/post-flow-release-finish
+++ b/post-flow-release-finish
@@ -1,38 +1,28 @@
 #!/bin/sh
-#
-# Runs at the end of git flow release finish
-#
-# Positional arguments:
-# $1    The version (including the version prefix)
-# $2    The origin remote
-# $3    The full branch name (including the release prefix)
-#
-VERSION=$1
-ORIGIN=$2
-BRANCH=$3
-
-# Implement your script aere.
+REPO_DIR=$(git rev-parse --show-toplevel)
+DOT_GIT_DIR=$(git rev-parse --git-dir)
+if [ "$DOT_GIT_DIR" = ".git" ]; then
+  DOT_GIT_DIR="$REPO_DIR"/"$DOT_GIT_DIR"
+fi
+HOOKS_DIR="$DOT_GIT_DIR"/hooks
 . "$HOOKS_DIR"/gitflow-functions
-ROOTDIR=$(git rev-parse --show-toplevel)
 
-git checkout $DEVELOP_BRANCH
-TMPFILE=$(mktemp --suffix=.gitflow)
+source "$HOOKS_DIR/config.sh"
 
-gitflow_set_major_minor $VERSION
-AVH_MINOR=$(($AVH_MINOR+1))
-AVH_PATCH_LEVEL=0
-gitflow_set_dev_release
-gitflow_build_version
+HOOK_ERROR=0
 
-LINENUMBER=$(($(grep -m1 -n "^#### " $ROOTDIR/Changes.mdown | cut -f1 -d:) -1 ))
-sed ''$LINENUMBER'a#### '$AVH_VERSION' =\n* Preparation for new development cycle.\n' $ROOTDIR/Changes.mdown > $TMPFILE
-cp $TMPFILE $ROOTDIR/Changes.mdown
+for module in $post_flow_release_finish_modules; do
+    module_path="$HOOKS_MODULES_DIR/$module"
+    [ ! -e $module_path ] && continue
+    . "$HOOKS_MODULES_DIR/$module"
+    if [ $? -eq 1 ] ; then
+        HOOK_ERROR=1
+    fi
+done
 
-gitflow_update_version $AVH_VERSION "Preparation for new development cycle after release $VERSION"
-
-git checkout $BRANCH
-#Clean up
-rm -f $TMPFILE
-
-# To terminate the git-flow action, return a non-zero exit code.
-exit 0
+if [ $HOOK_ERROR -eq 1 ] ; then
+  echo -e $'\e[31mPost flow release modules did not complete successfully... release finish cancelled\e[0m'
+else
+  echo -e $'\e[32mNo errors... release finished\e[0m'
+fi
+exit $HOOK_ERROR
